#
#
NEWSBIN=drn-bin
DIST=dist/drn

DIST_DIR=$(DIST)/www/$(NEWSBIN)/
BIN_DIR=$(DIST)/bin/
SETUP_DIR=$(DIST)/www/drn-setup/

make clean depend install_drn install_ddn install_dist:
	@echo 'Use gmake'
	gmake $*
